# Generated by Django 6.0.6 on 2026-06-12 18:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('items', models.JSONField()),
                ('address', models.CharField(max_length=255)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('restaurant', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('awaiting_courier', 'Awaiting courier'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered')], default='created', max_length=32)),
                ('status_message', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
